version: '3.7'

services:
  spring-api-gateway:
    image: zbalogh/reservation-spring-api-gateway:latest
    ports:
      - "8000:8000"
    restart: always
    networks:
      - zbalogh-reservation-network

  webgui-server:
    image: zbalogh/reservation-angular-ui:latest
    ports:
      - "8050:8050"
    restart: always
    networks:
      - zbalogh-reservation-network

  api-server:
    image: zbalogh/reservation-api-server:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - "postgres-server"
    environment:
      DB_HOSTNAME: postgres-server
      DB_PORT: 5432
      DB_NAME: zbaloghspringdemo
      DB_USERNAME: postgres
      DB_PASSWORD: 123dbsecret
      RESERVATION_AUTH_SERVER_NAME: auth-server
    networks:
      - zbalogh-reservation-network

  auth-server:
    image: zbalogh/reservation-dotnet-auth-server:latest
    ports:
      - "5000:5000"
      - "5002:5002"
    restart: always
    depends_on:
      - "postgres-server"
    networks:
      - zbalogh-reservation-network

  postgres-server:
    image: postgres:9.6
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123dbsecret
      POSTGRES_DB: zbaloghspringdemo
    volumes:
      - psql-reservation-data-volume:/var/lib/postgresql/data
    networks:
      - zbalogh-reservation-network

volumes:
  psql-reservation-data-volume:

networks:
  zbalogh-reservation-network:
