apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.authServiceName }}

spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    component: auth-server
  ports:
    - name: auth-server-web-port
      port: 5000
      targetPort: 5000
      nodePort: 31950
    - name: auth-server-grpc-port
      port: 5002
      targetPort: 5002
      nodePort: 31952
