apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: {{ .Release.Name }}-ingress

spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.webguiServiceName }}
          servicePort: 80

      - path: /web-gui/angular-gui/*
        backend:
          serviceName: {{ .Values.webguiServiceName }}
          servicePort: 80

      - path: /web-gui/angular-gui
        backend:
          serviceName: {{ .Values.webguiServiceName }}
          servicePort: 80

      - path: /api/data/*
        backend:
          serviceName: {{ .Values.apiServiceName }}
          servicePort: 8080

      - path: /api/auth/*
        backend:
          serviceName: {{ .Values.authServiceName }}
          servicePort: 5000
