FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

EXPOSE 5000
EXPOSE 5002

WORKDIR /workspace

ENV ASPNETCORE_URLS=http://+:5000
ENV ASPNETCORE_HTTP_PORT=5000

RUN dotnet tool install --global dotnet-watch
ENV PATH="${PATH}:/root/.dotnet/tools"

COPY . ./

RUN dotnet restore

CMD ["dotnet", "watch", "run"]
