# Default values are defined here.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

databaseName: zbaloghspringdemo

databaseServiceName: postgres-cluster-ip-service

databasePort: "5432"

databaseUserName: postgres

# default database password. It can be overriden by CLI parameter.
databasePassword: 123dbsecret

# default admin user password. It can be overriden by CLI parameter.
adminUserPassword: adm1w4K6B8

webguiServiceName: webgui-cluster-ip-service

apiServiceName: api-server

authServiceName: auth-server

webguiReplicas: "1"

apiServerReplicas: "2"

authServerReplicas: "1"

webguiImage: zbalogh/reservation-angular-ui

apiServerImage: zbalogh/reservation-api-server

authServerImage: zbalogh/reservation-dotnet-auth-server

alldeskNumber: "200"

# The supported Ingress Controller types: "aks", "gke", "istio", "nginx"
ingressControllerType: nginx
