apiVersion: apps/v1
kind: Deployment

metadata:
    name: webgui-deployment

spec:
    replicas: 1
    minReadySeconds: 15
    
    selector:
        matchLabels:
            component: webgui

    strategy:
        rollingUpdate:
          maxSurge: 50%
          maxUnavailable: 50%
        type: RollingUpdate

    template:
        metadata:
            labels:
                component: webgui
        spec:
            containers:
            - name: angular-ui
              image: zbalogh/reservation-angular-ui:latest
              imagePullPolicy: Always
              readinessProbe:
                  httpGet:
                    path: /health.html
                    port: 80
                  initialDelaySeconds: 15
                  periodSeconds: 30
              ports:
                - containerPort: 80
            restartPolicy: Always
