apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  rules:
  - http:
      paths:
      - path: /api/data/.*
        backend:
          serviceName: {{ .Values.apiServiceName }}
          servicePort: 8080

      - path: /api/auth/.*
        backend:
          serviceName: {{ .Values.authServiceName }}
          servicePort: 5000

      - path: /web-gui/angular-gui/.*
        backend:
          serviceName: {{ .Values.webguiServiceName }}
          servicePort: 80

      - path: /web-gui/angular-gui
        backend:
          serviceName: {{ .Values.webguiServiceName }}
          servicePort: 80

      - path: /
        backend:
          serviceName: {{ .Values.webguiServiceName }}
          servicePort: 80
