# Default values for csemeteborze-gke.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

databaseName: zbaloghspringdemo

databaseServiceName: postgres-cluster-ip-service

databasePort: "5432"

databaseUserName: postgres

databasePassword: MTIzZGJzZWNyZXQ=

webguiServiceName: webgui-cluster-ip-service

apiServiceName: api-server

authServiceName: auth-server

webguiReplicas: "1"

apiServerReplicas: "2"

authServerReplicas: "1"

webguiImage: zbalogh/reservation-angular-ui

apiServerImage: zbalogh/reservation-api-server

authServerImage: zbalogh/reservation-dotnet-auth-server

alldeskNumber: "200"
