apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-istio-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Release.Name }}-istio-gateway
  http:
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: {{ .Values.webguiServiceName }}
            port:
              number: 80
    - match:
        - uri:
            prefix: /web-gui/angular-gui
      route:
        - destination:
            host: {{ .Values.webguiServiceName }}
            port:
              number: 80
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: {{ .Values.apiServiceName }}
            port:
              number: 8080
