apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-postgres-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: database-server

  template:
    metadata:
      labels:
        component: database-server
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-database-pvc
      containers:
        - name: database-server
          image: postgres:9.6
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: {{ .Release.Name }}-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: {{ .Release.Name }}-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: {{ .Release.Name }}-secret
