apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-secret

data:
  DB_PASSWORD: {{ .Values.databasePassword | b64enc }}
  ADMIN_USER_PASSWORD: {{ .Values.adminUserPassword | b64enc }}

type: Opaque

# kubectl create secret generic reservation-secret --from-literal=DB_PASSWORD=123dbsecret
# echo -n 123dbsecret | base64
#
# MTIzZGJzZWNyZXQ=
# YWRtMXc0SzZCOA==
