# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular GUI Build

#on:
#  push:
#    branches: [ main ]
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project-sources/frontend/angular-gui
    env:
      APP_VERSION: "1.0.4"

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run npm install
      run: npm install

    - name: Build Angular Project
      run: npm run bp-dist

    - name: Docker Build and Push
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: zbalogh/reservation-angular-ui
        tags: latest, ${{ env.APP_VERSION }}
        registry: docker.io
        directory: project-sources/frontend/angular-gui
        dockerfile: project-sources/frontend/angular-gui/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
