apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.apiServiceName }}

spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    component: api-backend
  ports:
    - name: api-server-port
      port: 8080
      targetPort: 8080
      nodePort: 31900
