apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.webguiServiceName }}

spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    component: webgui
  ports:
    - name: webgui-port
      port: 80
      targetPort: 80
      nodePort: 31800
