apiVersion: apps/v1
kind: Deployment

metadata:
    name: {{ .Release.Name }}-webgui-deployment

spec:
    replicas: {{ .Values.webguiReplicas }}
    minReadySeconds: 15
    
    selector:
        matchLabels:
            component: webgui

    strategy:
        rollingUpdate:
          maxSurge: 50%
          maxUnavailable: 50%
        type: RollingUpdate

    template:
        metadata:
            labels:
                component: webgui
        spec:
            containers:
            - name: angular-ui
              image: {{ .Values.webguiImage }}:{{ .Chart.AppVersion }}
              imagePullPolicy: Always
              readinessProbe:
                  httpGet:
                    path: /health.html
                    port: 8050
                  initialDelaySeconds: 15
                  periodSeconds: 30
              ports:
                - containerPort: 8050
            restartPolicy: Always
